---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ceph
    daemon: mgr
  name: ceph-mgr
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
      daemon: mgr
  template:
    metadata:
      name: ceph-mgr
      namespace: ceph
      labels:
        app: ceph
        daemon: mgr
    spec:
      serviceAccount: default
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["ceph"]
              - key: daemon
                operator: In
                values: ["mgr"]
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: readonly-ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: readonly-ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: readonly-ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: readonly-ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: readonly-ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
        - name: ceph-conf
          emptyDir: {}
        - name: ceph-bootstrap-osd-keyring
          emptyDir: {}
        - name: ceph-bootstrap-mds-keyring
          emptyDir: {}
        - name: ceph-bootstrap-rgw-keyring
          emptyDir: {}
        - name: ceph-bootstrap-rbd-keyring
          emptyDir: {}
      initContainers:
        - name: copy-secrets
          image: busybox:1.29.3
          command: ["sh", "-c", "cp -LuR /secrets/. /"]
          volumeMounts:
            # Read only secrets
            - name: readonly-ceph-conf
              mountPath: /secrets/etc/ceph
            - name: readonly-ceph-bootstrap-osd-keyring
              mountPath: /secrets/var/lib/ceph/bootstrap-osd
            - name: readonly-ceph-bootstrap-mds-keyring
              mountPath: /secrets/var/lib/ceph/bootstrap-mds
            - name: readonly-ceph-bootstrap-rgw-keyring
              mountPath: /secrets/var/lib/ceph/bootstrap-rgw
            - name: readonly-ceph-bootstrap-rbd-keyring
              mountPath: /secrets/var/lib/ceph/bootstrap-rbd
            # Copied files
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
      containers:
        - name: ceph-mgr
          image: ceph/daemon:master-2ecd979-mimic-centos-7-x86_64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6800
            - containerPort: 7000
              name: dashboard
          env:
            - name: CEPH_DAEMON
              value: MGR
            - name: KV_TYPE
              value: k8s
            - name: NETWORK_AUTO_DETECT
              value: "4"
            - name: CLUSTER
              value: ceph
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
          livenessProbe:
              tcpSocket:
                port: 6800
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6800
              timeoutSeconds: 5
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
